version: '2'

services:
  mysql:
    container_name: "db_thunderdemo_1"
    image: mysql:5.6
    volumes:
      - ./binlog.cnf:/etc/mysql/conf.d/binlog.cnf
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "sudoku"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

